# Generated by Django 2.2 on 2019-05-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date_create_comment',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
