version: "3"
services:
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'task-db'
        MYSQL_USER: 'root'
        MYSQL_PASSWORD: 'root123'
        MYSQL_ROOT_PASSWORD: 'root123'
    web:
      build: .
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - .:/my_app_dir
      ports:
        - "8000:8000"
      depends_on:
        - db