# Generated by Django 2.2.1 on 2019-05-31 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='spent_time',
            field=models.IntegerField(default=0),
        ),
    ]
