# Generated by Django 2.2.1 on 2019-05-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='task',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('inprocess', 'inprocess'), ('finished', 'finished')], default='created', max_length=1),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
