# Generated by Django 2.2.1 on 2019-05-31 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Time',
        ),
    ]
