# Generated by Django 2.2.1 on 2019-05-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20190517_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('inprocess', 'inprocess'), ('finished', 'finished')], default='created', max_length=10),
        ),
    ]
