<<<<<<< HEAD
# Generated by Django 2.2.1 on 2019-05-31 14:31
=======
# Generated by Django 2.2.1 on 2019-05-31 14:32
>>>>>>> 6831745effaf679a6c0732f9a11fe05bffdd929f

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('start_time', models.DateTimeField(auto_now=True, null=True)),
=======
                ('start_time', models.DateTimeField()),
>>>>>>> 6831745effaf679a6c0732f9a11fe05bffdd929f
                ('finish_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.Task')),
            ],
        ),
    ]
