# Generated by Django 2.2.1 on 2019-05-31 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetracker',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timetracker',
            name='finish_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
