# Generated by Django 2.2.1 on 2019-05-31 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracker', '0002_auto_20190531_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetracker',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
