# Generated by Django 2.2.1 on 2019-05-31 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracker', '0003_auto_20190531_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetracker',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
