# Generated by Django 2.2.1 on 2019-05-31 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracker', '0004_auto_20190531_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetracker',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
